-- Compare Monthly Billing Calculations
-- This query compares different methods of calculating monthly billing
-- Parameter: :custId (Customer ID)

-- METHOD 1: Group by START_DT (Current Telegram Bot Method)
WITH daily_billing AS (
    SELECT
        T11.ID_VALUE AS MSN,
        :custId AS CUSTID,
        T4.D1_USAGE_ID AS USAGEID,
        T1.START_DT,
        T1.END_DT,
        SUM(T2.AUDIT_CALC_AMT) AS DAILY_CHARGES,
        T5.QUANTITY
    FROM CI_BSEG T1
    INNER JOIN CI_BSEG_CALC_LN T2 ON T1.BSEG_ID=T2.BSEG_ID
    INNER JOIN C1_USAGE T3 ON T1.BSEG_ID=T3.BSEG_ID
    INNER JOIN D1_USAGE T4 ON T3.USAGE_ID=T4.USG_EXT_ID
    INNER JOIN D1_USAGE_PERIOD_SQ T5 ON T4.D1_USAGE_ID=T5.D1_USAGE_ID
    INNER JOIN D1_MEASR_COMP T9 ON T5.MEASR_COMP_ID=T9.MEASR_COMP_ID
    INNER JOIN D1_DVC_CFG T10 ON T9.DEVICE_CONFIG_ID=T10.DEVICE_CONFIG_ID
    INNER JOIN D1_DVC_IDENTIFIER T11 ON T10.D1_DEVICE_ID=T11.D1_DEVICE_ID AND T11.DVC_ID_TYPE_FLG='D1SN'
    WHERE T1.BSEG_STAT_FLG<>'60'
        AND T1.SA_ID = (
            SELECT E3.SA_ID FROM CI_SA_SP E1, CI_SA E3
            WHERE E1.SP_ID=(
                SELECT SP_ID FROM CI_SP_CHAR
                WHERE CHAR_TYPE_CD='CM_LEGCY' AND ADHOC_CHAR_VAL=:custId AND ROWNUM=1
            )
            AND E3.SA_TYPE_CD='PPD' AND E3.SA_ID=E1.SA_ID AND ROWNUM=1
        )
        AND T2.CALC_RULE_CD IN ('CM_TOTALCHRGE','SUM_OF_CHARGES','E_LTECOP','E_LTECPK','E_LTC2CN','E_LTC1OP','E_LTC1PK','CM_SUM_OF_CHG','E_LTD2SW','E_LTD1ED','E_LTD3BSOP','E_LTD3BOP','E_LTD3BPK')
        AND TRIM(T5.D1_TOU_CD) IS NULL
        AND TRIM(T5.D1_SQI_CD) IS NULL
        AND T5.D1_UOM_CD='KWH'
    GROUP BY
        T1.SA_ID, T1.BSEG_ID, T1.START_DT, T1.END_DT,
        T4.D1_USAGE_ID, T5.QUANTITY, T11.ID_VALUE, T5.MEASR_COMP_ID
),
method1_start_dt AS (
    SELECT
        'METHOD 1 (START_DT)' AS METHOD,
        TO_CHAR(START_DT, 'YYYY-MM') AS MONTH_KEY,
        TO_CHAR(START_DT, 'Month YYYY') AS MONTH_NAME,
        COUNT(*) AS BILLING_DAYS,
        ROUND(SUM(DAILY_CHARGES), 2) AS TOTAL_CHARGES,
        ROUND(SUM(QUANTITY), 2) AS TOTAL_CONSUMPTION
    FROM daily_billing
    GROUP BY
        TO_CHAR(START_DT, 'YYYY-MM'),
        TO_CHAR(START_DT, 'Month YYYY')
),
method2_end_dt AS (
    SELECT
        'METHOD 2 (END_DT)' AS METHOD,
        TO_CHAR(END_DT, 'YYYY-MM') AS MONTH_KEY,
        TO_CHAR(END_DT, 'Month YYYY') AS MONTH_NAME,
        COUNT(*) AS BILLING_DAYS,
        ROUND(SUM(DAILY_CHARGES), 2) AS TOTAL_CHARGES,
        ROUND(SUM(QUANTITY), 2) AS TOTAL_CONSUMPTION
    FROM daily_billing
    GROUP BY
        TO_CHAR(END_DT, 'YYYY-MM'),
        TO_CHAR(END_DT, 'Month YYYY')
)
-- Combine both methods for comparison
SELECT * FROM method1_start_dt
UNION ALL
SELECT * FROM method2_end_dt
ORDER BY MONTH_KEY, METHOD;

-- To see differences side by side:
/*
SELECT
    COALESCE(m1.MONTH_KEY, m2.MONTH_KEY) AS MONTH,
    m1.METHOD AS METHOD_1,
    m1.TOTAL_CHARGES AS CHARGES_START_DT,
    m1.TOTAL_CONSUMPTION AS CONSUMPTION_START_DT,
    m2.METHOD AS METHOD_2,
    m2.TOTAL_CHARGES AS CHARGES_END_DT,
    m2.TOTAL_CONSUMPTION AS CONSUMPTION_END_DT,
    ROUND(m1.TOTAL_CHARGES - m2.TOTAL_CHARGES, 2) AS CHARGE_DIFFERENCE,
    ROUND(m1.TOTAL_CONSUMPTION - m2.TOTAL_CONSUMPTION, 2) AS CONSUMPTION_DIFFERENCE
FROM method1_start_dt m1
FULL OUTER JOIN method2_end_dt m2 ON m1.MONTH_KEY = m2.MONTH_KEY
ORDER BY COALESCE(m1.MONTH_KEY, m2.MONTH_KEY);
*/
