-- Customer Billing Details - Fixed ANSI JOIN syntax
-- Parameters: :custId (required), :startDate (optional), :endDate (optional)

SELECT
    billing.CUSTID,
    billing.MSN,
    billing.MOBILE_NO,
    billing.USAGEID,
    billing.START_DT,
    billing.END_DT,
    billing.DAILY_CHARGES,
    billing.MEASR_COMP_ID,
    billing.START_READ,
    billing.END_READ,
    billing.QUANTITY,
    billing.TOTAL_MONTHLY_AMOUNT
FROM (
    SELECT
        T11.ID_VALUE AS MSN,
        :custId AS CUSTID,
        T12.CONTACT_VALUE AS MOBILE_NO,
        T4.D1_USAGE_ID AS USAGEID,
        T1.START_DT,
        T1.END_DT,
        SUM(T2.AUDIT_CALC_AMT) AS DAILY_CHARGES,
        T5.MEASR_COMP_ID,
        T5.QUANTITY,
        T6.AUDIT_CALC_AMT AS TOTAL_MONTHLY_AMOUNT,
        MIN(USD.START_MSRMT) AS START_READ,
        MAX(USD.END_MSRMT) AS END_READ
    FROM CI_BSEG T1
    INNER JOIN CI_BSEG_CALC_LN T2 ON T1.BSEG_ID = T2.BSEG_ID
    INNER JOIN C1_USAGE T3 ON T1.BSEG_ID = T3.BSEG_ID
    INNER JOIN D1_USAGE T4 ON T3.USAGE_ID = T4.USG_EXT_ID
    INNER JOIN D1_USAGE_PERIOD_SQ T5 ON T4.D1_USAGE_ID = T5.D1_USAGE_ID
    INNER JOIN D1_US_CONTACT T7 ON T4.US_ID = T7.US_ID
    INNER JOIN D1_MEASR_COMP T9 ON T5.MEASR_COMP_ID = T9.MEASR_COMP_ID
    INNER JOIN D1_DVC_CFG T10 ON T9.DEVICE_CONFIG_ID = T10.DEVICE_CONFIG_ID
    INNER JOIN D1_DVC_IDENTIFIER T11 ON T10.D1_DEVICE_ID = T11.D1_DEVICE_ID AND T11.DVC_ID_TYPE_FLG = 'D1SN'
    INNER JOIN CI_SA SA ON T1.SA_ID = SA.SA_ID
    INNER JOIN CI_ACCT_PER AP ON SA.ACCT_ID = AP.ACCT_ID
    INNER JOIN C1_PER_CONTDET T12 ON AP.PER_ID = T12.PER_ID AND T12.CND_PRIMARY_FLG = 'C1YS'
    LEFT JOIN D1_USAGE_SCALAR_DTL USD ON USD.D1_USAGE_ID = T4.D1_USAGE_ID AND USD.MEASR_COMP_ID = T5.MEASR_COMP_ID
    LEFT JOIN CI_BSEG_CALC_LN T6 ON T6.BSEG_ID = T1.BSEG_ID
        AND T6.SEQNO = (SELECT MAX(M.SEQNO) FROM CI_BSEG_CALC_LN M
                        WHERE M.BSEG_ID = T1.BSEG_ID AND M.CALC_RULE_CD = 'E_TM_NLL')
    WHERE T1.BSEG_STAT_FLG <> '60'
        AND T1.SA_ID = (
            SELECT E3.SA_ID FROM CI_SA_SP E1
            INNER JOIN CI_SA E3 ON E3.SA_ID = E1.SA_ID AND E3.SA_TYPE_CD = 'PPD'
            WHERE E1.SP_ID = (SELECT SP_ID FROM CI_SP_CHAR
                              WHERE CHAR_TYPE_CD = 'CM_LEGCY' AND ADHOC_CHAR_VAL = :custId AND ROWNUM = 1)
            AND ROWNUM = 1
        )
        AND T2.CALC_RULE_CD IN (
            'CM_TOTALCHRGE', 'SUM_OF_CHARGES', 'E_LTECOP', 'E_LTECPK',
            'E_LTC2CN', 'E_LTC1OP', 'E_LTC1PK', 'CM_SUM_OF_CHG',
            'E_LTD2SW', 'E_LTD1ED', 'E_LTD3BSOP', 'E_LTD3BOP', 'E_LTD3BPK'
        )
        AND TRIM(T5.D1_TOU_CD) IS NULL
        AND TRIM(T5.D1_SQI_CD) IS NULL
        AND T5.D1_UOM_CD = 'KWH'
        AND (:startDate IS NULL OR T1.END_DT >= TO_DATE(:startDate, 'DD-MON-YYYY'))
        AND (:endDate IS NULL OR T1.END_DT <= TO_DATE(:endDate, 'DD-MON-YYYY'))
    GROUP BY
        T1.SA_ID, T1.BSEG_ID, T1.START_DT, T1.END_DT,
        T4.D1_USAGE_ID, T5.QUANTITY, T6.AUDIT_CALC_AMT,
        T12.CONTACT_VALUE, T11.ID_VALUE, T5.MEASR_COMP_ID
    ORDER BY T1.END_DT ASC
) billing
