-- Simple Monthly Billing Query
-- Based on your exact query structure, aggregated to monthly totals
-- Parameters: :F1 (Customer ID), :F2 (Start Date), :F3 (End Date)
-- Date Format: DD-MON-YYYY (e.g., '01-JAN-2025')

SELECT
    -- Month grouping
    TO_CHAR(billing.END_DT, 'YYYY-MM') AS MONTH_KEY,
    TO_CHAR(billing.END_DT, 'Month YYYY') AS MONTH_NAME,
    EXTRACT(YEAR FROM billing.END_DT) AS YEAR,

    -- Aggregated totals
    COUNT(*) AS BILLING_DAYS,
    ROUND(SUM(billing.DAILY_CHARGES), 2) AS TOTAL_CHARGES,
    ROUND(SUM(billing.QUANTITY), 2) AS TOTAL_CONSUMPTION,

    -- Meter and customer info (from any record in the month)
    MAX(billing.MSN) AS MSN,
    MAX(billing.CUSTID) AS CUSTID,
    MAX(billing.MOBILE_NO) AS MOBILE_NO,

    -- Latest balance in the month
    MAX(billing.PAYOFF_BAL) KEEP (DENSE_RANK LAST ORDER BY billing.END_DT) AS PAYOFF_BAL,

    -- Date range
    MIN(billing.START_DT) AS PERIOD_START,
    MAX(billing.END_DT) AS PERIOD_END

FROM (
    SELECT
        T11.ID_VALUE AS MSN,
        (SELECT ADHOC_CHAR_VAL FROM CI_SP_CHAR
         WHERE CHAR_TYPE_CD='CM_LEGCY' AND ADHOC_CHAR_VAL=:F1) AS CUSTID,
        T12.CONTACT_VALUE AS MOBILE_NO,
        T4.D1_USAGE_ID AS USAGEID,
        T1.START_DT,
        T1.END_DT,
        SUM(T2.AUDIT_CALC_AMT) AS DAILY_CHARGES,
        T5.MEASR_COMP_ID,
        T5.QUANTITY,
        T6.AUDIT_CALC_AMT AS TOTAL_MONTHLY_AMOUNT,
        (SELECT SUM(TOT_AMT) FROM CI_FT
         WHERE ACCOUNTING_DT <= T1.END_DT AND T1.SA_ID=SA_ID) AS PAYOFF_BAL
    FROM CI_BSEG T1
    LEFT JOIN CI_BSEG_CALC_LN T6 ON T6.BSEG_ID=T1.BSEG_ID
        AND T6.SEQNO=(SELECT MAX(M.SEQNO) FROM CI_BSEG_CALC_LN M
            WHERE M.BSEG_ID=T6.BSEG_ID AND M.CALC_RULE_CD='E_TM_NLL')
    INNER JOIN CI_BSEG_CALC_LN T2 ON T1.BSEG_ID=T2.BSEG_ID
    INNER JOIN C1_USAGE T3 ON T1.BSEG_ID=T3.BSEG_ID
    INNER JOIN D1_USAGE T4 ON T3.USAGE_ID=T4.USG_EXT_ID
    INNER JOIN D1_USAGE_PERIOD_SQ T5 ON T4.D1_USAGE_ID=T5.D1_USAGE_ID
    INNER JOIN D1_US_CONTACT T7 ON T4.US_ID=T7.US_ID
    INNER JOIN D1_MEASR_COMP T9 ON T5.MEASR_COMP_ID=T9.MEASR_COMP_ID
    INNER JOIN D1_DVC_CFG T10 ON T9.DEVICE_CONFIG_ID=T10.DEVICE_CONFIG_ID
    INNER JOIN D1_DVC_IDENTIFIER T11 ON T10.D1_DEVICE_ID=T11.D1_DEVICE_ID
        AND T11.DVC_ID_TYPE_FLG='D1SN'
    LEFT JOIN C1_PER_CONTDET T12 ON T12.PER_ID IN (
        SELECT PER_ID FROM CI_ACCT_PER WHERE ACCT_ID IN (
            SELECT ACCT_ID FROM CI_ACCT WHERE ACCT_ID IN (
                SELECT ACCT_ID FROM CI_SA WHERE SA_ID=T1.SA_ID
            )
        )
    ) AND T12.CND_PRIMARY_FLG='C1YS'
    WHERE T1.BSEG_STAT_FLG<>'60'
        AND T1.SA_ID = (
            SELECT E3.SA_ID FROM CI_SA_SP E1, CI_SA E3
            WHERE E1.SP_ID=(
                SELECT SP_ID FROM CI_SP_CHAR
                WHERE CHAR_TYPE_CD='CM_LEGCY' AND ADHOC_CHAR_VAL=:F1
            )
            AND E3.SA_TYPE_CD='PPD' AND E3.SA_ID=E1.SA_ID
        )
        AND T2.CALC_RULE_CD IN ('CM_TOTALCHRGE','SUM_OF_CHARGES','E_LTECOP','E_LTECPK','E_LTC2CN','E_LTC1OP','E_LTC1PK','CM_SUM_OF_CHG','E_LTD2SW','E_LTD1ED','E_LTD3BSOP','E_LTD3BOP','E_LTD3BPK')
        AND T1.END_DT BETWEEN :F2 AND :F3
        AND TRIM(T5.D1_TOU_CD) IS NULL
        AND TRIM(T5.D1_SQI_CD) IS NULL
        AND T5.D1_UOM_CD='KWH'
    GROUP BY
        T1.SA_ID, T1.BSEG_ID, T1.START_DT, T1.END_DT,
        T4.D1_USAGE_ID, T5.QUANTITY, T6.AUDIT_CALC_AMT,
        T12.CONTACT_VALUE, T11.ID_VALUE, T5.MEASR_COMP_ID
) billing
GROUP BY
    TO_CHAR(billing.END_DT, 'YYYY-MM'),
    TO_CHAR(billing.END_DT, 'Month YYYY'),
    EXTRACT(YEAR FROM billing.END_DT)
ORDER BY TO_CHAR(billing.END_DT, 'YYYY-MM') ASC;
