-- Customer Monthly Billing Summary
-- Aggregates daily billing data into monthly totals
-- Parameters: :custId (Customer ID), :startDate (optional), :endDate (optional)

WITH daily_billing AS (
    SELECT
        T11.ID_VALUE AS MSN,
        :custId AS CUSTID,
        T12.CONTACT_VALUE AS MOBILE_NO,
        T4.D1_USAGE_ID AS USAGEID,
        T1.START_DT,
        T1.END_DT,
        SUM(T2.AUDIT_CALC_AMT) AS DAILY_CHARGES,
        T5.MEASR_COMP_ID,
        T5.QUANTITY,
        T6.AUDIT_CALC_AMT AS TOTAL_MONTHLY_AMOUNT,
        (SELECT SUM(TOT_AMT) FROM CI_FT WHERE ACCOUNTING_DT <= T1.END_DT AND T1.SA_ID=SA_ID) AS PAYOFF_BAL
    FROM CI_BSEG T1
    LEFT JOIN CI_BSEG_CALC_LN T6 ON T6.BSEG_ID=T1.BSEG_ID
        AND T6.SEQNO=(SELECT MAX(M.SEQNO) FROM CI_BSEG_CALC_LN M
            WHERE M.BSEG_ID=T6.BSEG_ID AND M.CALC_RULE_CD='E_TM_NLL')
    INNER JOIN CI_BSEG_CALC_LN T2 ON T1.BSEG_ID=T2.BSEG_ID
    INNER JOIN C1_USAGE T3 ON T1.BSEG_ID=T3.BSEG_ID
    INNER JOIN D1_USAGE T4 ON T3.USAGE_ID=T4.USG_EXT_ID
    INNER JOIN D1_USAGE_PERIOD_SQ T5 ON T4.D1_USAGE_ID=T5.D1_USAGE_ID
    INNER JOIN D1_US_CONTACT T7 ON T4.US_ID=T7.US_ID
    INNER JOIN D1_MEASR_COMP T9 ON T5.MEASR_COMP_ID=T9.MEASR_COMP_ID
    INNER JOIN D1_DVC_CFG T10 ON T9.DEVICE_CONFIG_ID=T10.DEVICE_CONFIG_ID
    INNER JOIN D1_DVC_IDENTIFIER T11 ON T10.D1_DEVICE_ID=T11.D1_DEVICE_ID AND T11.DVC_ID_TYPE_FLG='D1SN'
    LEFT JOIN C1_PER_CONTDET T12 ON T12.PER_ID IN (
        SELECT PER_ID FROM CI_ACCT_PER WHERE ACCT_ID IN (
            SELECT ACCT_ID FROM CI_ACCT WHERE ACCT_ID IN (
                SELECT ACCT_ID FROM CI_SA WHERE SA_ID=T1.SA_ID
            )
        )
    ) AND T12.CND_PRIMARY_FLG='C1YS'
    WHERE T1.BSEG_STAT_FLG<>'60'
        AND T1.SA_ID = (
            SELECT E3.SA_ID FROM CI_SA_SP E1, CI_SA E3
            WHERE E1.SP_ID=(
                SELECT SP_ID FROM CI_SP_CHAR
                WHERE CHAR_TYPE_CD='CM_LEGCY' AND ADHOC_CHAR_VAL=:custId AND ROWNUM=1
            )
            AND E3.SA_TYPE_CD='PPD' AND E3.SA_ID=E1.SA_ID AND ROWNUM=1
        )
        AND T2.CALC_RULE_CD IN ('CM_TOTALCHRGE','SUM_OF_CHARGES','E_LTECOP','E_LTECPK','E_LTC2CN','E_LTC1OP','E_LTC1PK','CM_SUM_OF_CHG','E_LTD2SW','E_LTD1ED','E_LTD3BSOP','E_LTD3BOP','E_LTD3BPK')
        AND TRIM(T5.D1_TOU_CD) IS NULL
        AND TRIM(T5.D1_SQI_CD) IS NULL
        AND T5.D1_UOM_CD='KWH'
        AND (:startDate IS NULL OR T1.END_DT >= TO_DATE(:startDate, 'DD-MON-YYYY'))
        AND (:endDate IS NULL OR T1.END_DT <= TO_DATE(:endDate, 'DD-MON-YYYY'))
    GROUP BY
        T1.SA_ID, T1.BSEG_ID, T1.START_DT, T1.END_DT,
        T4.D1_USAGE_ID, T5.QUANTITY, T6.AUDIT_CALC_AMT,
        T12.CONTACT_VALUE, T11.ID_VALUE, T5.MEASR_COMP_ID
),
daily_with_reads AS (
    SELECT
        db.*,
        (SELECT MIN(m1.START_MSRMT) FROM D1_USAGE_SCALAR_DTL m1
         WHERE m1.D1_USAGE_ID=db.USAGEID AND m1.MEASR_COMP_ID=db.MEASR_COMP_ID) AS START_READ,
        (SELECT MAX(m1.END_MSRMT) FROM D1_USAGE_SCALAR_DTL m1
         WHERE m1.D1_USAGE_ID=db.USAGEID AND m1.MEASR_COMP_ID=db.MEASR_COMP_ID) AS END_READ
    FROM daily_billing db
)
SELECT
    -- Group by END_DT month (billing month)
    TO_CHAR(END_DT, 'YYYY-MM') AS MONTH_KEY,
    TO_CHAR(END_DT, 'Month') AS MONTH_NAME,
    EXTRACT(YEAR FROM END_DT) AS YEAR,

    -- Aggregated values
    COUNT(*) AS BILLING_DAYS,
    ROUND(SUM(DAILY_CHARGES), 2) AS TOTAL_CHARGES,
    ROUND(SUM(QUANTITY), 2) AS TOTAL_CONSUMPTION,

    -- Date range for the month
    MIN(START_DT) AS MONTH_START_DATE,
    MAX(END_DT) AS MONTH_END_DATE,

    -- Latest balance (from last record in the month)
    MAX(PAYOFF_BAL) KEEP (DENSE_RANK LAST ORDER BY END_DT) AS LATEST_PAYOFF_BAL,

    -- Customer info (from first record)
    MAX(MSN) AS MSN,
    MAX(CUSTID) AS CUSTID,
    MAX(MOBILE_NO) AS MOBILE_NO

FROM daily_with_reads
GROUP BY
    TO_CHAR(END_DT, 'YYYY-MM'),
    TO_CHAR(END_DT, 'Month'),
    EXTRACT(YEAR FROM END_DT)
ORDER BY TO_CHAR(END_DT, 'YYYY-MM') ASC
